spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://117.17.142.207:3306/real_test?useSSL=false&serverTimezone=UTC
    username: root
    password: cs616
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2