spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/real_test?useSSL=false&serverTimezone=UTC
    username: root
    password: 461352
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2