spring:
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:log4jdbc:mysql://117.17.142.207:3306/real_test?useSSL=false&serverTimezone=UTC
    username: root
    password: cs616
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
  http:
    converters:
      preferred-json-mapper: jackson

